baseurl = "https://bookdown.org/"
relativeurls = true
languageCode = "en-us"
title = "Bookdown"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "render_post"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "â†©"

[[menu.logo]]
    name = "Bookdown"
    pre = "//bookdown.org/yihui/bookdown/images/logo.png"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Documentation"
    url = "http://bookdown.org/yihui/bookdown/"
    weight = 3
[[menu.main]]
    name = "Books"
    url = "/archive/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
[[menu.main]]
    name = "Authors"
    url = "/authors/"
    weight = 6
[[menu.main]]
    name = "Contest"
    url = "/contest/"
    weight = 7
[[menu.main]]
    name = "Log in"
    url = "http://bookdown.org/connect/"
    weight = 8

[[menu.icons]]
    name = "Github"
    post = "github"
    url = "https://github.com/rstudio/bookdown"
    weight = 1
[[menu.icons]]
    name = "Twitter"
    post = "twitter"
    url = "https://twitter.com/rstudio"
    weight = 2
[[menu.icons]]
    name = "RSS"
    post = "rss"
    url = "/index.xml"
    weight = 3

[params]
    description = "Write HTML, PDF, ePub, and Kindle books with R Markdown"
    footer = "&copy; [RStudio, Inc.](https://www.rstudio.com) 2016 -- 2019"
